name: Deploy to staging server

on:
  push:
    branches:
      - staging

jobs:
  staging:
    uses: ./.github/workflows/base.yml
    with:
      environment: STAGING
      project_path: MedConnect/frontend
      branch: staging
      web_server: "nginx"
      process_manager: "pm2"
      install_command: "npm install"
      build_command: "npm run build"
    secrets:
      ssh_private_key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
      password: ${{ secrets.STAGING_PASSWORD }}
      server_ip: ${{ secrets.STAGING_SERVER_IP }}
      username: ${{ secrets.STAGING_USERNAME }}